import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useState, useEffect } from 'react'

export default function Navbar(props) {
  const [toggle, setToggle] = useState("flex scale-y-0 md:scale-y-0")
  const handleToggle = () => {
    let x = toggle === "flex scale-y-0 md:scale-y-0" ? 'flex md:scale-y-0' : 'flex scale-y-0 md:scale-y-0'
    setToggle(x)
  }
  const primary='opacity-0 h-1 ';
  const secondary='bg-green-500 h-1 ';
  let [homeColor, aboutColor, contactColor] = [primary, primary, primary];
  switch (props.page) {
    case 'home':
      homeColor = secondary;
      break;
    case 'about':
      aboutColor = secondary;
      break;
    case 'contact':
      contactColor = secondary;
      break;
  }


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <nav className="bg-gray-800/70 md:flex hidden transition-colors duration-[10ms]">

        <Link href={'/Home'}><a><div className="text-white text-lg p-3 hover:bg-pink-600 w-auto cursor-pointer">Home</div><div className={homeColor+"w-auto"}></div></a></Link>
        <Link href={'/About'}><a><div className="text-white text-lg p-3 hover:bg-pink-600 w-auto cursor-pointer">About</div><div className={aboutColor+"w-auto"}></div></a></Link>
        <Link href={'/Contact'}><a><div className="text-white text-lg p-3 hover:bg-pink-600 w-auto cursor-pointer">Contact</div><div className={contactColor+"w-auto"}></div></a></Link>
      

          <div className="flex-grow mt-auto">
          <div className={primary}> </div>
          </div>

          <div className="flex flex-col justify-end">
            <div className="flex">
        <input className="m-2 p-1 shadow rounded flex" type="search" placeholder='search'/>
        <div><button className="bg-transparent hover:bg-blue-500 text-blue-700 hover:text-white m-2 py-1 ml-0 px-2 border border-blue-500 hover:border-transparent rounded">Button </button>
        
        </div></div>
        <div className={primary+"w-auto"}></div>
        </div>







      </nav>

      <nav className="bg-gray-800/70 md:hidden flex items-center"><button className="" onClick={handleToggle} >
        <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 m-1 p-1 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button></nav>



      <nav className={"transition-[transform] origin-top bg-gray-800/70 flex-col " + toggle}>
        <Link href="#"><a><div className="text-white text-lg p-3 mx-4 mt-2 hover:bg-pink-600/80 text-center cursor-pointer">Home</div></a></Link>
        <Link href="#"><a><div className="text-white text-lg p-3 mx-4 hover:bg-pink-600/80 text-center cursor-pointer">About</div></a></Link>
        <Link href="#"><a><div className="text-white text-lg p-3 mx-4 hover:bg-pink-600/80 text-center cursor-pointer">Contact</div></a></Link>
        <input className="mx-4 mt-2 mb-1 p-2 shadow rounded flex-e" type="search" placeholder='search' />
        <button className="bg-transparent hover:bg-blue-500 text-blue-700 hover:text-white mx-4 py-1 mt-1 mb-2 px-2 border border-blue-500 hover:border-transparent rounded">Button</button>

      </nav>




    </div>
  )
}
